name: 'Snowkelus'
description: 'GitHub Action to start a http server that serves files..'
author: 'Snowkelus <openpatents@snowkel.us>'
branding:
  icon: 'server'
  color: 'orange'
runs:
  using: 'node16'
