name: 'Snowkelus'
description: 'GitHub Action Container to Automate Github README, and also other things like an Aggregator for example..'
author: 'Snowkelus <openpatents@snowkel.us>'
branding:
  icon: 'server'
  color: 'orange'
runs:
  using: 'node16'
  entrypoint: 'sven.sh'
