name: 'Snowkelus'
description: 'GitHub Action Container to Automate Github README, and also other things like an Aggregator for example..'
author: 'Snowkelus <openpatents@snowkel.us>'
branding:
  icon: 'server'
  color: 'orange'
inputs:
  sven:  # id of input
    description: 'Sven, Greetings!'
    required: true
    default: 'Hello, World!'
outputs:
  greets:
    description: 'Greetings!'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sven }}
